### ISSUE TITLE
Component to search by "common name" - from the home page -

### ISSUE THREAD

**Issue by PJTeel** [PJTeel/unit3-birdapp#3]

**Comment by MarkS2145** [comment]
Paula, Liliana, 

I am pleased to say I have created the initial Search.js Component and have built out a basic framework and understanding of how we can get user input.  I am attaching an image that shows the current capabilities and output.  I
![837CA1C9-3D48-42A1-B2A5-4746C5DFA8BA](https://user-images.githubusercontent.com/74433887/109261040-10867d00-77b4-11eb-9729-580efa16d50b.jpeg)
 [](URL)

Key NOTES:
1) The drop down list populates from dummy data at this stage.
2) The checkboxes are active.  
3) I have not applied any css at this stage as we don't have a design theme determined at this early stage.

**Next steps.**... 
I would appreciate your feedback to help us refine our search scope based on key user stories for our bronze deliverable.

Cheers,

Mark
